#!/bin/bash

data_path="$HOME/.local/share/quran-cli"
bookmark_file="$HOME/.local/share/quran-cli/data/bookmark.csv"
bin_path="$HOME/.local/bin"

echo "quran-cli Installation Script"
echo "============================="

echo "Cloning the repository..."
git clone https://github.com/SaminYaser-work/quran-cli.git ~/quran-cli

echo "Installing..."
cp ~/quran-cli/quran "$bin_path"

#TODO: backup old bookmark file if exists
if [[ -f "$data_path" ]]; then
    cp -r ~/quran-cli/data ~/.local/share/quran-cli/
else
    mkdir -p "$data_path"
    cp -r ~/quran-cli/data "$data_path"
fi

echo "Cleaning up..."
rm -rf ~/quran-cli
