#!/usr/bin/env bash
########################################################################################################
#                                                                                            ..    .   #
#                                                                                      x .d88"    @88> #
#                x.    .        .u    .                  u.    u.                       5888R     %8P  #
#     .u@u     .@88k  z88u    .d88B :@8c        u      x@88k u@88c.                .    '888R      .   #
#  .zWF8888bx ~"8888 ^8888   ="8888f8888r    us888u.  ^"8888""8888"           .udR88N    888R    .@88u #
# .888  9888    8888  888R     4888>'88"  .@88 "8888"   8888  888R           <888'888k   888R   ''888E`#
# I888  9888    8888  888R     4888> '    9888  9888    8888  888R           9888 'Y"    888R     888E #
# I888  9888    8888  888R     4888>      9888  9888    8888  888R           9888        888R     888E #
# I888  9888    8888 ,888B .  .d888L .+   9888  9888    8888  888R  88888888 9888        888R     888E #
# `888Nx?888   "8888Y 8888"   ^"8888*"    9888  9888   "*88*" 8888" 88888888 ?8888u../  .888B .   888& #
#  "88" '888    `Y"   'YP        "Y"      "888*""888"    ""   'Y"             "8888P'   ^*888%    R888"#
#        88E                               ^Y"   ^Y'                            "P'       "%       ""  #
#        98>                                                                                           #
#        '8                                                                                            #
#         `                                                                                            #
#                                                                                                      #
#      Get the English translation of the verbatim word of Allah, the only God worthy of worship,      #
#                                  Right in your terminal.                                             #
########################################################################################################

# Github: https://github.com/SaminYaser-work/quran-cli
#
#
# Licensed under GNU GENERAL PUBLIC LICENSE Version 3 (GPLv3)
#
# Copyright (C) 2022 Samin Yaser
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

###########################################
# Variables
###########################################

# data_path="$HOME/.local/share/quran-cli/data"
data_path="./data"

file="$data_path/saheeh_english_fn.csv"
metadata="$data_path/metadata.csv"
bookmark_file="$data_path/bookmark.csv"

# Styling
if [ -x /usr/bin/tput ] && tput setaf 1 &>/dev/null; then
  BOLD=$(tput bold)
  RESET=$(tput sgr0)
  UNDERLINE=$(tput smul)
  NOUNDERLINE=$(tput rmul)
  RED=$(tput setaf 1)
  NC=$(tput sgr0)
else
  BOLD="\033[1m"
  UNDERLINE="\033[4m"
  NOUNDERLINE="\033[0m"
  RESET="\033[0m"
  RED='\033[0;31m' # Red
  NC='\033[0m'
fi

# Sed replacements
remove_verse_number='sed "s/([0-9]\+) //g"'
remove_footnote_number='sed "s/\[[0-9]\+\]//g"'
verse_number_in_bold='sed "s/\(([0-9]\+)\)/${BOLD}\1${RESET}/g"'
footnote_number_in_italics='sed "s/\([[0-9]\+]\)/${UNDERLINE}\1${NOUNDERLINE}/g"'
insert_new_line='sed "s/;;/\n\n/g"'
replace_blank_notes='sed "s/::blank::/No notes available/g"'
footnote_del_blank_line='sed "/::blank::/{N;d;}"'

###########################################
# Functions
###########################################

# Error checking functions
# --------------------------
check_ayah_exists_in_a_surah() {
  num_of_ayahs=$(awk -F, -v surah="$1" '$1 == surah {print $2}' $metadata)
  if [[ $2 -gt $num_of_ayahs || $2 -lt 1 ]]; then
    echo -e "${RED}Error:${NC} Surah $(get_surah_name_transliterated "$1") only has $num_of_ayahs ayahs."
    exit 1
  fi
}

check_surah_exists() {
  if [[ $1 -gt 114 || $1 -lt 1 ]]; then
    echo -e "${RED}Error:${NC} There are only 114 surahs in the Noble Quran."
    exit 1
  fi
}

check_verse_exists() {
  if [[ $1 -gt 6236 || $1 -lt 1 ]]; then
    echo -e "${RED}Error:${NC} There are only 6236 verses in the Noble Quran."
    exit 1
  fi
}

check_bookmark_file() {
  if [[ ! -f $bookmark_file ]]; then
    echo -e "${RED}Bookmark file doesn't exist!${NC}"
    exit 1
  fi

  total_bookmarks=$(($(wc -l <$bookmark_file) - 1))

  if [[ $total_bookmarks -lt 1 ]]; then
    echo "No bookmarks found."
    exit 1
  fi
}

check_valid_bookmark() {
  if [[ $1 -gt $(($(wc -l <$bookmark_file) - 1)) || $1 -lt 1 ]]; then
    echo -e "${RED}Error:${NC} Invalid bookmark number."
    exit 1
  fi
}

# Get functions
# ----------------

display_center() {
  columns="$(tput cols)"
  while IFS= read -r line; do
    printf "%*s\n" $(((${#line} + columns) / 2)) "$line"
  done <"$1"
}

# Metadata : _index,_ayas,_start,_name,_tname,_ename,_type,_order,_rukus
# Column No:    1      2     3     4      5      6      7     8      9

# Get the title (in English, transliteration & Arabic) of the surah
get_surah_title() {
  local res
  res=$(awk -F, -v surah="$1" '$1 == surah {print $4 " | " $5 " ("$6")"}' "$metadata")
  # echo -e "${BOLD}$res${RESET}"
  display_center <(echo -e "${UNDERLINE}${BOLD}$res${RESET}${NOUNDERLINE}")
}

# Get the transliterated name of the surah
get_surah_name_transliterated() {
  local res
  res=$(awk -F, -v surah="$1" '$1 == surah {print $5}' "$metadata")
  echo -e "${BOLD}$res${RESET}"
}

get_surah_title_by_verse() {
  local res
  res=$(awk -F, -v verse="$1" '$3+1 > verse {print f;exit;} {f=$4 " | " $5 " ("$6")"}' "$metadata") # Prints the line before the match is found
  display_center <(echo -e "${UNDERLINE}${BOLD}$res${RESET}${NOUNDERLINE}")
}

save_bookmark() {
  if [[ ! -f $bookmark_file ]]; then
    echo "No bookmark file found. Creating a new one in $bookmark_file..."
    if touch $bookmark_file; then
      echo "Created new bookmark file at $bookmark_file"
      echo "Surah|Ayah|Date" >$bookmark_file
    else
      echo "Failed to create bookmark file at $bookmark_file."
      exit 1
    fi
  fi

  echo "$1|$2|$(date)" >>$bookmark_file &&
    echo "Bookmark saved." && exit 0

  echo "Failed to write to bookmark file at $bookmark_file."
  exit 1
}

show_bookmarks() {
  check_bookmark_file
  column -t -s '|' $bookmark_file
}

select_bookmark() {
  check_bookmark_file
  check_valid_bookmark "$1"

  s=$(awk -F '|' -v b="$1" 'NR==(b+1) {print $1}' $bookmark_file)
  a=$(awk -F '|' -v b="$1" 'NR==(b+1) {print $2}' $bookmark_file)
  get_surah_title "$s"
  echo
  get_ayah_of_a_surah "$s" "$a"
  print_footnotes "$s" "$a"
}

delete_bookmark() {
  check_bookmark_file
  check_valid_bookmark "$1"

  x=$(($1 + 1))

  sed -i "${x}d" $bookmark_file
  echo "Bookmark deleted."
}

# Prints full information about the surah
get_surah_info() {
  local res
  res=$(awk -F, -v surah="$1" '$1 == surah {print "Index: " $1 "\nNumber of Ayahs: " $2 "\nStarting Verse Number: " $3+1 "\nName: " $4 "\nName (Transliterated): " $5 "\nName (Translation): " $6 "\nType: " $7 "\nOrder: " $8 "\nNumber of Rukūʿ: " $9}' "$metadata")
  echo "$res"
}

get_all_ayahs() {
  local res
  res=$(awk -F "|" '{print $4""}' $file)
  echo "$res"
}

get_all_notes() {
  local res
  res=$(awk -F '|' '{print $5"\n"}' "$file" | eval "$insert_new_line" | eval "$replace_blank_notes")
  echo "$res"
}

# TODO: Format output nicely
get_full_quran() {
  local res
  res=$(awk -F '|' '{print $4"|"$5}' "$file" | sed "s/;;/ /g" | eval "$replace_blank_notes")
  echo "$res"
}

get_full_surah() {
  local res
  res=$(awk -F "|" -v s="$1" '$2 == s {print $4"\n"}' $file)
  echo "$res"
}

get_full_notes() {
  local res
  res=$(awk -F '|' -v s="$1" '$2 == s {print $5"\n"}' "$file" | eval "$insert_new_line" | eval "$footnote_del_blank_line")
  echo "$res"
}

get_ayahs_in_range() {
  local res
  res=$(awk -F '|' -v s="$1" -v a1="$2" -v a2="$3" '$2 == s && $3 >= a1 && $3 <= a2 {print $4"\n"}' "$file")
  echo "$res"
}

get_footnotes_in_range() {
  local res
  res=$(awk -F '|' -v s="$1" -v a1="$2" -v a2="$3" '$2 == s && $3 >= a1 && $3 <= a2 {print $5"\n"}' "$file" | eval "$insert_new_line" | eval "$footnote_del_blank_line")
  echo "$res"
}

# Get a single ayah without verse number and references
get_ayah_of_a_surah_simple() {
  local res
  res=$(awk -F "|" -v s="$1" -v a="$2" '$2 == s && $3 == a {print $4}' $file | eval "$remove_verse_number" | eval "$remove_footnote_number")
  echo "$res"
}

get_ayah_of_a_surah() {
  local res
  res=$(awk -F "|" -v s="$1" -v a="$2" '$2 == s && $3 == a {print $4 "\n"}' $file | eval "$verse_number_in_bold" | eval "$footnote_number_in_italics")
  echo -e "$res"
}

get_verse() {
  local res
  res=$(awk -F "|" -v a="$1" '$1 == a {print $4 "\n"}' $file | eval "$verse_number_in_bold" | eval "$footnote_number_in_italics")
  echo "$res"
}

get_verse_note() {
  local res
  res=$(awk -F "|" -v a="$1" '$1 == a {print $5 "\n"}' $file | eval "$insert_new_line" | eval "$footnote_del_blank_line")
  echo "$res"
}

get_footnotes_of_ayah_in_a_surah() {
  local res
  res=$(awk -F '|' -v s="$1" -v a="$2" '$2 == s && $3 == a {print $5 "\n"}' $file | eval "$insert_new_line" | eval "$footnote_del_blank_line")
  echo "$res"
}

get_footnote_header() {
  echo
  echo -e "${UNDERLINE}Footnotes:${NOUNDERLINE}"
  echo
}

print_footnotes() {
  if [[ "$#" -eq 1 ]]; then
    footnotes=$(get_verse_note "$1")
  else
    footnotes=$(get_footnotes_of_ayah_in_a_surah "$1" "$2")
  fi
  if [[ -n $footnotes ]]; then
    get_footnote_header
    echo "$footnotes"
  fi
  exit 0
}

print_footnotes_in_range() {
  footnotes=$(get_footnotes_in_range "$1" "$2" "$3")
  if [[ -n $footnotes ]]; then
    get_footnote_header
    echo "$footnotes"
  fi
  exit 0
}

# TODO: Print a help message
print_help() {
  printf "Usage: Under construction\nFor now, please refer to the README.md file on GitHub.\nhttps://github.com/SaminYaser-work/quran-cli"
}

###########################################
# Parsing arguments
###########################################

# variables
surah="$1"
ayah="$2"
range=0

# Flags
show_help=0
full_quran_mode=0
simple_mode=0
verse_mode=0
info_mode=0
range_mode=0

while getopts 'ahls:v:i:B:b:d:r:' opt; do
  case "$opt" in
  h)
    show_help=1
    ;;

  a) # TODO: Implement this feature
    full_quran_mode=1
    echo "This feature is not yet implemented."
    exit 1
    ;;

  s)
    simple_mode=1
    surah="$2"
    ayah="$3"
    ;;

  v)
    verse_mode=1
    verse_number="$OPTARG"
    ;;

  i)
    info_mode=1
    surah="$2"
    ;;

  r)
    range_mode=1
    surah="$2"
    ayah="$3"
    range="$4"
    ;;

  B)
    save_bookmark "$OPTARG" "$3"
    exit 0
    ;;

  b)
    select_bookmark "$OPTARG"
    exit 0
    ;;

  d)
    delete_bookmark "$OPTARG"
    exit 0
    ;;

  l)
    show_bookmarks
    exit 0
    ;;

  :)
    print_help
    exit 1
    ;;

  ?)
    print_help
    exit 1
    ;;
  esac
done
shift "$((OPTIND - 1))"

###########################################
# Printing results
###########################################

# Show help message if no arguments are passed or if '-h' flag is given
if [[ $show_help -eq 1 || -z $surah ]]; then
  print_help
  exit 0
fi

# Info mode: Print inforamtion about a surah when '-i' flag is used
if [[ $info_mode -eq 1 ]]; then
  check_surah_exists "$surah"
  get_surah_info "$surah"
  exit 0
fi

# Checking if the surah number is valid
if [[ $verse_mode -eq 0 ]]; then
  check_surah_exists "$surah"
else
  check_verse_exists "$verse_number"
fi

# Range mode: Print ayahs in a range when '-r' flag is used
if [[ $range_mode -eq 1 ]]; then
  check_ayah_exists_in_a_surah "$surah" "$ayah"
  check_ayah_exists_in_a_surah "$surah" "$range"

  get_surah_title "$surah"
  echo
  get_ayahs_in_range "$surah" "$ayah" "$range"
  print_footnotes_in_range "$surah" "$ayah" "$range"
  exit 0
fi

# Verse mode: Print the ayah with verse number and references when '-v' flag is given
if [[ $verse_mode -eq 1 ]]; then
  get_surah_title_by_verse "$verse_number"
  echo
  get_verse "$verse_number"
  print_footnotes "$verse_number"
  exit 0
fi

# Simple mode: Just print the ayah without verse number and references when '-s' flag is given
if [[ $simple_mode -eq 1 ]]; then
  check_ayah_exists_in_a_surah "$surah" "$ayah"
  get_ayah_of_a_surah_simple "$surah" "$ayah"
  exit 0
fi

# The default output when no flags are passed
if [[ -z $2 ]]; then
  # Prints a full surah
  get_surah_title "$surah"
  echo
  get_full_surah "$surah"
  get_footnote_header
  get_full_notes "$surah"

else
  # Print a specific ayah of a surah
  check_ayah_exists_in_a_surah "$surah" "$ayah"
  get_surah_title "$surah"
  echo
  get_ayah_of_a_surah "$surah" "$ayah"
  print_footnotes "$surah" "$ayah"
fi
